### ISSUE TITLE
SEGFAULT while initializing

### ISSUE THREAD

**Issue by CodenameLambda** [CodenameLambda/DoAnimate#1]
The program terminates with a SIGSEGV even if the main function is empty.

**Comment by orwell96** [comment]
Here I am.

**Comment by CodenameLambda** [comment]
The source of the problem is somewhere in `types.cc` or `types.hh`. I don't know where though. (Tested by excluding the libraries `nodes` and `shapes`)

**Comment by CodenameLambda** [comment]
Hashing isn't the problem. The problem lies within `doanimate::types::implementation`.

**Comment by CodenameLambda** [comment]
There are actually two times a SEGFAULT happens: If `doanimate::types::implementation::TypeInfo::tuple` and the bunch are called (problem lies within `types.hh`) and when hashing for `doanimate::types::implementation::TypeInfo` takes place (problem lies within `types.cc`).

**Comment by CodenameLambda** [comment]
I won't use an `unordered_map` for the hash function of the key type again.
